### ISSUE TITLE
Bauchibred - Users can process faux mints/deposits in the vault

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-new-scope-judging#108]
Bauchibred

High

# Users can process faux mints/deposits in the vault

## Summary

Users can process faux mints/deposits in the vault due to the try/catch logic applied to skip some markets.

## Vulnerability Detail

Whenever minting/depositing in/to the vault there is a need to call the internal deposit to pass on the asset to the underlying Zerolend market: https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/vaults/CuratedVaultSetters.sol#L35-L42

```solidity
  function _deposit(address caller, address receiver, uint256 assets, uint256 shares) internal override {
    super._deposit(caller, receiver, assets, shares);

    _supplyPool(assets);

    // `lastTotalAssets + assets` may be a little off from `totalAssets()`.
    _updateLastTotalAssets(lastTotalAssets + assets);
  }
```

Problem however is that when supplying the assets to the pool, the query could revert and this would not bubble back up to the initial deposit attempt, this is because of the try/catch logic in the internal \_supplyPool: https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/vaults/CuratedVaultSetters.sol#L115-L144

```solidity
  function _supplyPool(uint256 assets) internal {
    for (uint256 i; i < supplyQueue.length; ++i) {
      IPool pool = supplyQueue[i];

      uint256 supplyCap = config[pool].cap;
      if (supplyCap == 0) continue;

      pool.forceUpdateReserve(asset());

      uint256 supplyShares = pool.supplyShares(asset(), positionId);

      // `supplyAssets` needs to be rounded up for `toSupply` to be rounded down.
      (uint256 totalSupplyAssets, uint256 totalSupplyShares,,) = pool.marketBalances(asset());
      uint256 supplyAssets = supplyShares.toAssetsUp(totalSupplyAssets, totalSupplyShares);

      uint256 toSupply = UtilsLib.min(supplyCap.zeroFloorSub(supplyAssets), assets);

      if (toSupply > 0) {
        // Using try/catch to skip markets that revert.
        try pool.supplySimple(asset(), address(this), toSupply, 0) {
          assets -= toSupply;
        } catch {}
      }

      if (assets == 0) return;
    }

    if (assets != 0) revert CuratedErrorsLib.AllCapsReached();
  }

```

As the comment suggests the logic is applied in order to skip markets that revert, issue however is that this can then be used by a malicious actor to bypass whatever checks are in the validation logic.

Note, going down to the implementation of `supplySimple` we see that it's just like the classic `supply` implementation, see the two methods here: [Pool.sol#L67-L80](https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/Pool.sol#L67-L80).

Now both end up validating the execution in the validationLogic.sol with https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/ValidationLogic.sol#L70-L89

```solidity
  function validateSupply(
    DataTypes.ReserveCache memory cache,
    DataTypes.ReserveData storage reserve,
    DataTypes.ExecuteSupplyParams memory params,
    DataTypes.ReserveSupplies storage totalSupplies
  ) internal view {
    require(params.amount != 0, PoolErrorsLib.INVALID_AMOUNT);

    (bool isFrozen,) = cache.reserveConfiguration.getFlags();
    require(!isFrozen, PoolErrorsLib.RESERVE_FROZEN);

    uint256 supplyCap = cache.reserveConfiguration.getSupplyCap();

    require(
      supplyCap == 0
        || ((totalSupplies.supplyShares + uint256(reserve.accruedToTreasuryShares)).rayMul(cache.nextLiquidityIndex) + params.amount)
          <= supplyCap * (10 ** cache.reserveConfiguration.getDecimals()),
      PoolErrorsLib.SUPPLY_CAP_EXCEEDED
    );
  }
```

This then means that anyone can sidestep all the requirements here, since even if the checks revert it doesn't bubble up [here](https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/vaults/CuratedVaultSetters.sol#L115-L143).

## Impact

All requirements made in the `validateSupply` can be sidestepped, which makes this of high impact considering reserves are set in the frozen state as a measure to combat any black swan event, however users can still process withdrawals even when the reserves are frozen sidestepping this.

Additionally, just to reiterate, this would mean that if for whatever reason the underlying supply fails the deposit/mint in the vault still gets processed, that's to say another example would be that if the supply cap has been surpassed for a reserve the attempt at minting shares/depositing in the vault [should revert during the validation](https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/ValidationLogic.sol#L87), however due to the [try/catch logic](https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/vaults/CuratedVaultSetters.sol#L133-L136) even if the validation reverts, the function still continues its flow as normal and instead the vault still mints these tokens, albeit they would be wrongly backed per the SUPPLY_CAP limit existing.

## Code Snippet

- https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/vaults/CuratedVaultSetters.sol#L35-L42

- https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/ValidationLogic.sol#L87
- https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/vaults/CuratedVaultSetters.sol#L133-L136

## Tool used

Manual Review

## Recommendation

Do not use a try/catch logic when depositing assets to the underlying Zerolend markets.

Duplicate of #102

**Comment by Bauchibred** [comment]
This should be rejudged, it was initially duplicated to #102 and then rejected without any comment, imo this is valid and should be fixed as it allows anyone to process faux deposits.

**Comment by bG9zZXIvZmFpbHVyZQ** [comment]
Escalate on behalf of @Bauchibred

**Comment by sherlock-admin3** [comment]
> Escalate on behalf of @Bauchibred 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
We have no impact here. 

The try/catch block is added there because if a pool reverts, it can pass to the next without reverting the whole function. 

```solidity
      if (toSupply > 0) {
        // Using try/catch to skip markets that revert.
        try pool.supplySimple(asset(), address(this), toSupply, 0) {
          assets -= toSupply;
        } catch {}
      }
```
The requirements in `validateSupply()` can't be bypassed because if the function reverts, we go directly to the catch block, and nothing happens. 

This means we won't subtract `toSupply` from `assets`. Nothing happens, and the function continues to the next pool.

I am planning to reject the escalation and leave the issue as is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Duplicate of #102

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [bG9zZXivZmFpbHVyZQ](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/108/#issuecomment-2394073273): rejected
