### ISSUE TITLE
Bauchibred - Invalid prices would be ingested and used to finalize core functionalities

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-06-new-scope-judging#109]
Bauchibred

Medium

# Invalid prices would be ingested and used to finalize core functionalities

## Summary

Pricing data being ingested would be wrong during flash crashes for some assets which would affect core functionalities since no checks for Chainlink's circuit breakers are being made and the Aggregator's min/maxAnswers would be ingested.

## Vulnerability Detail

Take a look at https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/PoolGetters.sol#L158-L164

```solidity
  function getAssetPrice(address reserve) public view override returns (uint256) {
    (, int256 price,, uint256 updatedAt,) = IAggregatorV3Interface(_reserves[reserve].oracle).latestRoundData();
    require(price > 0, 'Invalid price');
    require(block.timestamp <= updatedAt + 1800, 'Stale Price');
    return uint256(price);
  }

```

This function is used in order to cover any functionality that requires prices in protocol.

Now from the readMe, protocol is to integrate multiple standard tokens: https://github.com/sherlock-audit/2024-06-new-scope/blob/main/README.md#L14-L17

```markdown
### Q: If you are integrating tokens, are you allowing only whitelisted tokens to work with the codebase or any complying with the standard? Are they assumed to have certain properties, e.g. be non-reentrant? Are there any types of [weird tokens](https://github.com/d-xo/weird-erc20) you want to integrate?

Only standard ERC20 tokens + USDC and BNB are in-scope

---
```

Issue however is that there are no checks being implemented to ensure the prices returned are not at the circuit breakers, considering Chainlink has a min/max price for some of it's supported assets and whenever the price of the asset goes lower/higher than the low/high boundaries of the asset respectively, the boundaries get returned instead, which in our case would mean that the wrong price is being used here: https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L328-L373

```solidity
  function _calculateAvailableCollateralToLiquidate(
    DataTypes.ReserveData storage collateralReserve,
    DataTypes.ReserveCache memory debtReserveCache,
    uint256 debtToCover,
    uint256 userCollateralBalance,
    uint256 liquidationBonus,
    uint256 collateralPrice,
    uint256 debtAssetPrice,
    uint256 liquidationProtocolFeePercentage
  ) internal view returns (uint256, uint256, uint256) {
    AvailableCollateralToLiquidateLocalVars memory vars;

    vars.collateralPrice = collateralPrice; // oracle.getAssetPrice(collateralAsset);
    vars.debtAssetPrice = debtAssetPrice; // oracle.getAssetPrice(debtAsset);

    vars.collateralDecimals = collateralReserve.configuration.getDecimals();
    vars.debtAssetDecimals = debtReserveCache.reserveConfiguration.getDecimals();

    unchecked {
      vars.collateralAssetUnit = 10 ** vars.collateralDecimals;
      vars.debtAssetUnit = 10 ** vars.debtAssetDecimals;
    }

    // This is the base collateral to liquidate based on the given debt to cover
    vars.baseCollateral = ((vars.debtAssetPrice * debtToCover * vars.collateralAssetUnit)) / (vars.collateralPrice * vars.debtAssetUnit);

    vars.maxCollateralToLiquidate = vars.baseCollateral.percentMul(liquidationBonus);

    if (vars.maxCollateralToLiquidate > userCollateralBalance) {
      vars.collateralAmount = userCollateralBalance;
      vars.debtAmountNeeded = (
        (vars.collateralPrice * vars.collateralAmount * vars.debtAssetUnit) / (vars.debtAssetPrice * vars.collateralAssetUnit)
      ).percentDiv(liquidationBonus);
    } else {
      vars.collateralAmount = vars.maxCollateralToLiquidate;
      vars.debtAmountNeeded = debtToCover;
    }

    if (liquidationProtocolFeePercentage != 0) {
      vars.bonusCollateral = vars.collateralAmount - vars.collateralAmount.percentDiv(liquidationBonus);
      vars.liquidationProtocolFee = vars.bonusCollateral.percentMul(liquidationProtocolFeePercentage);
      return (vars.collateralAmount - vars.liquidationProtocolFee, vars.debtAmountNeeded, vars.liquidationProtocolFee);
    } else {
      return (vars.collateralAmount, vars.debtAmountNeeded, 0);
    }
  }
```

## Impact

Wrong prices would be ingested and used to decide core functionalities, this is because when liquidating, this means the [wrong amount of users asset would be liquidated](https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L339-L341) if the wrong price is used, causing them a loss of funds:
https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L139-L148

```solidity
  function executeLiquidationCall(
    // ..snip
    _calculateAvailableCollateralToLiquidate(
      collateralReserve,
      vars.debtReserveCache,
      vars.actualDebtToLiquidate,
      vars.userCollateralBalance,
      vars.liquidationBonus,
      IPool(params.pool).getAssetPrice(params.collateralAsset),
      IPool(params.pool).getAssetPrice(params.debtAsset),
      IPool(params.pool).factory().liquidationProtocolFeePercentage()
    );
    // ..snip
}
```

## Code Snippet

- https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/PoolGetters.sol#L158-L164
- https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L328-L373

## Tool used

Manual Review

## Recommendation

Check the aggregators min/max breakers and ensure that the prices returned are not at these boundaries, if they are, a good way to sort this out would be to include some sort of fallback oracle logic.

The latter can be seen as what's implemented [in the forked AAVE](https://github.com/aave-dao/aave-v3-origin/blob/6948864fc7e74b2b29fadfe2007998992060f84b/src/core/contracts/misc/AaveOracle.sol#L101).

Duplicate of #74

**Comment by Bauchibred** [comment]
I didn't even know that excerpt existed in the rulebook, that's besides the point though. What I don't understand however is how we are using this line of thought to invalidate the report, if the protocol have explicitly indicated that they support USDC and this has been indicated in this report?. Escalating to indicate that, if [this escalation](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/74#issuecomment-2390975294) is accepted, then this report should be counted as a duplicate imo since it fulfils all the [duplication requirements](https://github.com/sherlock-protocol/sherlock-v2-docs/tree/e7dc89270b05f8d2fcee69dc4204c7a2b8fb4cf9/audits/judging/judging#ix-duplication-rules) on the rule book and the rulebook has indicated the subjective nature of issues and how judges are allowed to see some issues  beyond the purview of the rulebook.

So leaving to HOJ to decide.

**Comment by bG9zZXIvZmFpbHVyZQ** [comment]
Escalate on behalf of @Bauchibred

**Comment by sherlock-admin3** [comment]
> Escalate on behalf of @Bauchibred 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
In the last contest, I was a judge, and there was exactly the same case.
 
If the price feeds are not mentioned, then the issue is invalid. This rule was added a few months ago and must be followed. 

https://docs.sherlock.xyz/audits/real-time-judging/judging#viii.-list-of-issue-categories-that-are-considered-valid

There is no exception to be made now because it would be very unfair to the Watsons from previous contests and to the ones in this contest who followed the rules.

> **Chainlink Price Checks**: Issues related to minAnswer and maxAnswer checks on Chainlink's Price Feeds are considered medium **only** if the Watson explicitly mentions the price feeds (e.g. USDC/ETH) that require this check.

Planning to reject the escalation and leave the issue as is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Duplicate of #74

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [bG9zZXivZmFpbHVyZQ](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/109/#issuecomment-2394075004): accepted
