### ISSUE TITLE
000000 - Users might not be able to repay their debt fully using the NFT position manager

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-new-scope-judging#264]
000000

Medium

# Users might not be able to repay their debt fully using the NFT position manager

## Summary
Users might not be able to repay their debt fully using the NFT position manager
## Vulnerability Detail
Users can interact with the NFT position manager in order to earn rewards using a staking mechanism. The NFT position manager essentially manages positions in the `Pool` contract. Thus, users can do different operations that are possible in the `Pool` contract like supplying and borrowing. One of the lines we have in the repayment flow in the `Pool` contract is this one:
```solidity
    if (params.amount == type(uint256).max) {
      params.amount = payback.assets;
    }
```
The goal is for the users to be able to fully repay their loan as they have no way of predicting the amount of debt their position will have at the time of the transaction (as it grows with `block.timestamp`). In order to repay their loan using the position manager, they will call this function:
```solidity
  function repay(AssetOperationParams memory params) external {
    if (params.asset == address(0)) revert NFTErrorsLib.ZeroAddressNotAllowed();
    IERC20Upgradeable(params.asset).safeTransferFrom(msg.sender, address(this), params.amount);
    _repay(params);
  }
```
The function transfers the provided amount to the NFT position manager contract and then it calls `_repay()`. Just based on the transfer, we can clearly see that the functionality where the user provides `type(uint256).max` in order to fully repay the loan is impossible as there is no way he has that amount of assets (if the pool asset is actually a legit token). In the `_repay()` function, we have this line:
```solidity
DataTypes.SharesType memory repaid = pool.repay(params.asset, params.amount, params.tokenId, params.data);
```
The line calls the `repay()` function on the pool with the provided amount and then we eventually go here:
```solidity
    payback.assets = balances.getDebtBalance(cache.nextBorrowIndex);

    // Allows a user to max repay without leaving dust from interest.
    if (params.amount == type(uint256).max) {
      params.amount = payback.assets;
    }
```
We already saw some of these lines. First, we get the debt and then we check whether the amount is `type(uint256).max` which as mentioned, is impossible if interacting with the position manager. Due to the way the rest of the function is coded, if the user has actually provided an amount >= the debt, we would actually be able to fully repay the debt. Then, we have this line back in the position manager:
```solidity
if (currentDebtBalance == 0 && repaid.assets < params.amount) {
      asset.safeTransfer(msg.sender, params.amount - repaid.assets);
    }
```
If the user has fully repaid the loan and has provided a bigger amount than what was repaid, we refund him. So the user could theoretically fully repay his debt by providing an amount >= the debt and then getting the excess (if >) back. Firstly, we can completely ignore the scenario where the user provides amount equal to the debt as it is pretty much impossible for that to happen due to the borrow index growing based on `block.timestamp`. That leaves two options, the user trying to fully repay his debt but providing amount lower than the debt and a scenario where he provides more than the debt. The first scenario makes it so he didn't fully repay his debt which is not what he actually wanted. The second scenario would work in a good amount of cases but here are a few issues that can occur
- The user is supposed to repay a certain amount of debt but he is forced to pay more funds than the debt, however he doesn't actually have those extra funds and he won't be able to transfer them in initially to then get the refund
- The user has a bit more than what the debt would be at the time of execution, thus he is trying to pay just a bit more than the debt, however due to the unknown time of the transaction (due to `block.timestamp`), he actually underpays and still has debt

Both scenarios are possible as the user is forced to pay more than his debt and he might not even have that extra amount as he is not actually supposed to pay it but he is forced to do so if he actually wants to repay his debt.
## Impact
Users might not be able to repay their debt fully using the NFT position manager
## Code Snippet
https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/positions/NFTPositionManager.sol#L116-L120
## Tool used

Manual Review

## Recommendation
Handle the case where the user provides `type(uint256).max` as amount

**Comment by samuraii77** [comment]
Issue is valid and it is also different than #119. We can clearly see that we would revert here when providing `type(uint256).max` as the user does not have such an amount of funds:
```solidity
  function repay(AssetOperationParams memory params) external {
    if (params.asset == address(0)) revert NFTErrorsLib.ZeroAddressNotAllowed();
    IERC20Upgradeable(params.asset).safeTransferFrom(msg.sender, address(this), params.amount);
    _repay(params);
  }
```

**Comment by 0x3b33** [comment]
escalate per the above comment

**Comment by sherlock-admin3** [comment]
> escalate per the above comment

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
This issue has no impact.

In the issue, the impact is: 
> Users might not be able to repay their debt fully using the NFT position manager

The user can still repay his debt fully. He will call the function with the amount he needs. He will not call `repay()` with `amount = type(uint256).max`. This is a parameter controlled by the user. 

The worst-case scenario is that the function will revert and have to call it again.

Planning to reject the escalation and leave the issue as is.

**Comment by samuraii77** [comment]
@cvetanovv, the amount to repay grows with each second as interest. There is no way to provide the exact amount to repay as there is no way to predict the timestamp of the function execution. There will always be leftover or the function will revert.

**Comment by thongtrungtran** [comment]
Should be valid med because:
- The user can not repay all his debt by specify the amount he needs because of debt accrual. 
- The logic is intended to support users to repay all position debt which resolves the above point.
- Leaving debt in the protocol, even dust amounts, would be economic risk for the protocol

**Comment by cvetanovv** [comment]
@samuraii77 @thongtrungtran But he could pay 99.99% of his debt. After that, the remaining 0.01% will not increase with great speed because there is no big debt. So the remaining few wei will be easier to pay?

**Comment by samuraii77** [comment]
@cvetanovv, it still wouldn't be really possible to repay even if there's just a few wei left. Let's say the debt grows with 1 wei per second, this means that the user has to exactly time the function time execution based on a particular block timestamp second which is essentially impossible unless it's due to luck.

**Comment by thongtrungtran** [comment]
@cvetanovv the issue becomes more severe if it is debt in a high interest rate market. I think it cant be said that the remaining debt does not increase with great speed

**Comment by cvetanovv** [comment]
> @cvetanovv, it still wouldn't be really possible to repay even if there's just a few wei left. Let's say the debt grows with 1 wei per second, this means that the user has to exactly time the function time execution based on a particular block timestamp second which is essentially impossible unless it's due to luck.

If the user has, say, 100 wei left, will it continue to increase by 1 wei per second? 

My thought is that he can pay 99.99% and then pay the remaining 0.01% with no problem because they won't increase every second.

**Comment by samuraii77** [comment]
Even if it doesn't grow at 1 wei per second, it is still very likely that it might grow 1 wei while the function is being executed. A user might submit it to the mempool but then get executed like 10 minutes later or at an even later point.

I would agree that if a user really, really wants to make the repayment happen, it would happen eventually after a few repayments and that is if he really wants to actually repay it. However, that still classifies as an issue, it is clearly unintended and a forgotten case which breaks protocol functionality - users shouldn't have to tryhard to repay their loan trying to time the timestamp of the execution, repay multiple times and even then not be guaranteed a full repayment.

**Comment by cvetanovv** [comment]
My decision to reject the escalation remains.

**Comment by WangSecurity** [comment]
Result:
Invalid
Has duplicates

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0x3b33](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/264/#issuecomment-2390971952): rejected
