### ISSUE TITLE
Bigsam - Value obtained from Maxdeposit/Maxmint Value will revert when used for making deposit into the curated vault violating The compliance with ERC4626.

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-new-scope-judging#337]
Bigsam

Medium

# Value obtained from Maxdeposit/Maxmint Value will revert when used for making deposit into the curated vault violating The compliance with ERC4626.

### Summary

Curated Vaults are known to be ERC4626 fully compliant. 
The CuratorVault should follow the ERC4626 standard. -
https://audits.sherlock.xyz/contests/466#:~:text=The%20CuratorVault%20should%20follow%20the%20ERC4626%20standard.

Also check the documentation. - https://docs-one.zerolend.xyz/features/curated-and-cross-chain-vaults#:~:text=Curated%20Vaults%20are%20non%2Dcustodial%2C%20ERC4626%2Dcompliant%20vaults%20that%20enable%20users%20to%20deposit%20a

Zerolend's `_maxDeposit` and `_maxMint` functions overestimate the values returned for the maximum amount of assets that can be deposited into the curated vault, leading to reverts during the actual deposit process. The issue arises because 

1. the pool's supply cap is not considered in the `_maxDeposit` function, resulting in inaccurate values when the user tries to deposit based on the returned maximums. 

2.  Additionally, when a pool is frozen, the maximum deposit for that pool should be zero, but the current implementation does not account for this. These issues violate the ERC4626 specification and result in transaction failures.

### **maxDeposit**
Maximum amount of the underlying asset that can be deposited into the Vault for the receiver, through a deposit call.

MUST return the maximum amount of assets deposit would allow to be deposited for receiver and not cause a revert, which MUST NOT be higher than the actual maximum that would be accepted (it should underestimate if necessary). This assumes that the user has infinite assets, i.e.

https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/vaults/CuratedVaultGetters.sol#L130-L145

https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/ValidationLogic.sol#L76-L88

Without considering the FROZEN AND POOL CAP factors, we revert here

https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/vaults/CuratedVaultSetters.sol#L142
 

### Attack Path

The **MaxDeposit** and **MaxMint** functions in the curated vault should accurately return the maximum amount of assets that can be deposited into the vault without causing a revert during the deposit. However, two critical issues arise:

1. **Frozen Pools**: The current implementation does not consider whether a pool is frozen, which would prevent deposits from being made. According to the ERC4626 standard, if a pool is frozen, the max deposit amount should be returned as zero. However, in Zerolend, frozen pools are still included in the calculation, leading to incorrect values and potential reverts when users attempt deposits.

2. **Supply Cap Ignored**: The supply cap of the main pool where the deposit is being made is not factored into the `maxDeposit` calculation. This can result in overestimated values where the maximum deposit for the curated vault is considered, but not the pool’s supply cap. Consequently, users may attempt to deposit an amount that exceeds the pool's supply cap, causing the transaction to revert.

Example of the problematic logic in the `_maxDeposit` function:

```solidity
for (uint256 i; i < supplyQueue.length; ++i) {
  IPool pool = supplyQueue[i];

  uint256 supplyCap = config[pool].cap;
  if (supplyCap == 0) continue;

  uint256 supplyShares = pool.supplyShares(asset(), positionId);
  (uint256 totalSupplyAssets, uint256 totalSupplyShares,,) = pool.marketBalances(asset());

 @audit >>>>  uint256 supplyAssets = supplyShares.toAssetsUp(totalSupplyAssets, totalSupplyShares);
  @audit >>>>   totalSuppliable += supplyCap.zeroFloorSub(supplyAssets);
}
```

In this implementation:
- The function does not consider whether the pool is **frozen**, and therefore unable to accept new deposits.
- The **supply cap** of the underlying pool is not checked, which can lead to an overestimation of the maximum depositable amount.

---

### Impact

- **Transaction Reverts**: Users attempting to deposit the maximum returned by `maxDeposit` or `maxMint` can face transaction reverts if the pool's supply cap has been reached, or if the pool is frozen and unable to accept deposits.
- **ERC4626 Compliance Violation**: According to ERC4626 standards, the maxDeposit function must return the maximum amount of assets that can be transferred without reverting. The current implementation violates this standard by returning overestimated values.

```solidity
  /* LIQUIDITY ALLOCATION */

  /// @dev Supplies `assets` to ZeroLend.
  function _supplyPool(uint256 assets) internal {
    for (uint256 i; i < supplyQueue.length; ++i) {
      IPool pool = supplyQueue[i];

      uint256 supplyCap = config[pool].cap;
      if (supplyCap == 0) continue;

      pool.forceUpdateReserve(asset());

      uint256 supplyShares = pool.supplyShares(asset(), positionId);

      // `supplyAssets` needs to be rounded up for `toSupply` to be rounded down.
      (uint256 totalSupplyAssets, uint256 totalSupplyShares,,) = pool.marketBalances(asset());
      uint256 supplyAssets = supplyShares.toAssetsUp(totalSupplyAssets, totalSupplyShares);

      uint256 toSupply = UtilsLib.min(supplyCap.zeroFloorSub(supplyAssets), assets);

      if (toSupply > 0) {
        // Using try/catch to skip markets that revert.
        try pool.supplySimple(asset(), address(this), toSupply, 0) {
          assets -= toSupply;
        } catch {}
      }

      if (assets == 0) return;
    }

    if (assets != 0) revert CuratedErrorsLib.AllCapsReached();
  }
```

### Mitigation

To resolve this issue, the following modifications should be made to the `maxDeposit` function and related logic:

1. **Consider the Pool’s Supply Cap**: The function should be modified to return the **minimum** value between the curated vault's remaining depositable assets and the main pool's supply cap. This ensures that deposits do not exceed the supply cap of the underlying pool.

   Example of mitigation:

 ```solidity
++    uint256 supplyCap2 = cache.reserveConfiguration.getSupplyCap();

++    uint256 MainPoolRemaining = (supplyCap2 * (10 ** cache.reserveConfiguration.getDecimals()).zeroFloorSub((totalSupplies.supplyShares + uint256(reserve.accruedToTreasuryShares)).rayMul(cache.nextLiquidityIndex))
   
++    uint256 poolSupplyCapRemaining = supplyCap.zeroFloorSub(supplyAssets);
++   totalSuppliable += Math.min(poolSupplyCapRemaining, MainPoolRemaining);
  ```

2. **Frozen Pool Check**: Add a check for whether the pool is frozen. If the pool is frozen, the function should return zero for that pool, as no deposits can be made into a frozen pool.

   Example of mitigation:
 
```solidity
++   (bool isFrozen,) = cache.reserveConfiguration.getFlags();
++   if (isFrozen) {
++       continue;  // Skip this pool, as no deposits are allowed
++  }
   ```

3. **Ensure Accurate `maxDeposit` Return Values**: The returned `maxDeposit` value should accurately represent the maximum amount of assets that can be deposited into the pool without causing a revert. If a pool’s cap is reached, the function should return zero for that pool.

By implementing the mitigations, the `maxDeposit` function will now return accurate values that respect both the curated vault cap and the pool’s supply cap, while also considering whether the pool is frozen. This ensures compliance with ERC4626 and prevents reverts during deposit attempts.

---

Duplicate of #399

**Comment by Tomiwasa0** [comment]
Escalate

Wrongly Duplicated  - Different from MaxMint/MaxRedeem. 

>Per https://discord.com/channels/812037309376495636/1276194200676733020/1280465918459117618, only with H/M impact will it be validated

>The Sherlock Judge can use public statements up until 24h before the contest ends to override the language in the chosen source of truth.

>All likely invalid since most issues do not meet the DoS requirement of sherlock (no funds lock for more than a week, no time sensitive functions involved) and all are simply unused view functions

>Incorrect values in View functions are by default considered low.
Exception: In case any of these incorrect values returned by the view functions are used as a part of a larger function which would result in loss of funds then it would be a valid medium/high depending on the impact.


The above is false, the value obtained from the maxdeposit should never revert if this value is used it will revert and since the vault is a standard-compliant vault DOS of deposit is a Valid Medium.
 The EIP rule can be seen in this report.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Wrongly Duplicated  - Different from MaxMint/MaxRedeem. 
> 
> >Per https://discord.com/channels/812037309376495636/1276194200676733020/1280465918459117618, only with H/M impact will it be validated
> 
> >The Sherlock Judge can use public statements up until 24h before the contest ends to override the language in the chosen source of truth.
> 
> >All likely invalid since most issues do not meet the DoS requirement of sherlock (no funds lock for more than a week, no time sensitive functions involved) and all are simply unused view functions
> 
> >Incorrect values in View functions are by default considered low.
> Exception: In case any of these incorrect values returned by the view functions are used as a part of a larger function which would result in loss of funds then it would be a valid medium/high depending on the impact.
> 
> 
> The above is false, the value obtained from the maxdeposit should never revert if this value is used it will revert and since the vault is a standard-compliant vault DOS of deposit is a Valid Medium.
>  The EIP rule can be seen in this report.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Nihavent** [comment]
https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/431 is a dupe

**Comment by cvetanovv** [comment]
I disagree with the escalation.

HoJ has written in Discord that for this contest, issues related to ERC4626 should have at least a Medium impact.

That there is a chance that the transaction will revert is not sufficient for Medium severity: https://docs.sherlock.xyz/audits/real-time-judging/judging#v.-how-to-identify-a-medium-issue

Here you can see that the DoS of the deposit is not valid Medium (single block): https://docs.sherlock.xyz/audits/real-time-judging/judging#iii.-sherlocks-standards

Planning to reject the escalation and leave the issue as is.

**Comment by Tomiwasa0** [comment]
Context of this issues matters  and this can lead to an integration issue also. 
1.
>If the protocol team provides specific information in the README or CODE COMMENTS, that information stands above all judging rules. In case of contradictions between the README and CODE COMMENTS, the README is the chosen source of truth.

>The judge can decide that CODE COMMENTS are outdated based on contextual evidence. In that case, the judging guidelines are the chosen source of truth.

The Readme covers this SO the judging guideline should not stand.

2.

>is considered a DoS of a single block, hence only if the function is clearly time-sensitive, it can be a Medium severity issue.

from the second link you provided. If Zerolend grows massively like Aave which we believe it would, deposit the max available  is time-sensitive for the user who wants to deposit the available max. 


3.  All compliant 4626 vaults have an invariant which is stated in the EIP - MUST NOT REVERT. 

from the rule sent 

>What properties/invariants do you want to hold even if breaking them has a low/unknown impact?

>Issues that break the invariants from the above question, irrespective of whether the impact is low/unknown, will be assigned Medium severity.

https://docs.sherlock.xyz/audits/real-time-judging/judging#v.-how-to-identify-a-medium-issue:~:text=If%20the%20protocol%20team%20provides%20specific,are%20the%20chosen%20source%20of%20truth.

**Comment by cvetanovv** [comment]
@Tomiwasa0 

1. - Sherlock Judge can override the readme - https://docs.sherlock.xyz/audits/real-time-judging/judging#iii.-sherlocks-standards

> The Sherlock Judge can use public statements up until 24h before the contest ends to override the language in the chosen source of truth.

2. Potential issues are not valid for this contest - https://github.com/sherlock-audit/2024-06-new-scope?tab=readme-ov-file#q-should-potential-issues-like-broken-assumptions-about-function-behavior-be-reported-if-they-could-pose-risks-in-future-integrations-even-if-they-might-not-be-an-issue-in-the-context-of-the-scope-if-yes-can-you-elaborate-on-propertiesinvariants-that-should-hold

3. As I pointed out in point 1 the judge can rewrite these rules stating what changes - https://discord.com/channels/812037309376495636/1276194200676733020/1280465918459117618

My decision to reject the escalation remains.

**Comment by Tomiwasa0** [comment]
Noted. Thanks.

**Comment by WangSecurity** [comment]
Result:
Invalid
Duplicate of #399

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [Tomiwasa0](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/337/#issuecomment-2392049161): rejected
