### ISSUE TITLE
CL001 - DoS In Reallocate If One withdrawSimple function revert

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-new-scope-judging#359]
CL001

Medium

# DoS In Reallocate If One withdrawSimple function revert

### Summary

DoS In `Reallocate` If One `withdrawSimple` function revert

### Root Cause

Every` withdrawSimple()`  call could [revert](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/ValidationLogic.sol#L97) if the `amount` is zero.

When [`toWithdraw `= 0](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/vaults/CuratedVault.sol#L250),as[ this call ](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/vaults/CuratedVault.sol#L253)is not wrapped into a try-catch block, the transaction will revert and therefore the `Allocator` is not able to[ reallocates](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/vaults/CuratedVault.sol#L232) the vault's liquidity

### Internal pre-conditions

`Allocator` needs to call` reallocate() ` to reallocates the vault's liquidity

### Impact

DoS In Reallocate function.

### Mitigation

Wrap the[ withdrawSimple()](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/vaults/CuratedVault.sol#L253) call into a try-catch block as [_withdrawPool](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/vaults/CuratedVaultSetters.sol#L134)

**Comment by 0xjuaan** [comment]
Escalate

This does not seem to be a dupe of #434

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This does not seem to be a dupe of #434 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I agree with the escalation. 

This issue does not have any attack vector. It is described that the function will revert if the `toWithdraw` is zero. However, it does not describe how this would happen and why.

Planning to accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/359/#issuecomment-2393048823): accepted
