### ISSUE TITLE
charlesjhongc - _calculateDebt() return amount in incorrect uint

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-new-scope-judging#369]
charlesjhongc

High

# _calculateDebt() return amount in incorrect uint

### Summary

The `_calculateDebt()` used in `contracts/core/pool/logic/LiquidationLogic.sol` should return two normalized amount instead of amount in shares. These two amount will be considered as normalized in the rest calculation in `executeLiquidationCall()` and also used as the transfer amount of underlying tokens.

### Root Cause

https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L264

**Comment by charlesjhongc** [comment]
Escalate

I didn't know the impact field is a REQUIRED field to be considered as a valid issue since it's not specified in the doc nor is checked by the github bot. Also, it's marked as dup of a valid rewarded issue so I think it should not be considered as invalid.

The incorrect calculation is obvious and will cause unexpected behavior so I didn't explain the impact. Apologize for the inconvenience and will fix this for future audit.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I didn't know the impact field is a REQUIRED field to be considered as a valid issue since it's not specified in the doc nor is checked by the github bot. Also, it's marked as dup of a valid rewarded issue so I think it should not be considered as invalid.
> 
> The incorrect calculation is obvious and will cause unexpected behavior so I didn't explain the impact. Apologize for the inconvenience and will fix this for future audit.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I agree with the Lead Judge.

Same reason as one of your other issue. You can see my comment: https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/370#issuecomment-2399972144

Planning to reject the escalation and leave the issue as is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [charlesjhongc](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/369/#issuecomment-2393004424): rejected
