### ISSUE TITLE
charlesjhongc - amount `userCollateralBalance` is incorrect in liquidation

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-new-scope-judging#370]
charlesjhongc

High

# amount `userCollateralBalance` is incorrect in liquidation

### Summary

The `vars.userCollateralBalance` in `contracts/core/pool/logic/LiquidationLogic.sol#L136` should use normalized amount instead of amount in shares. This collateral balance is considered as real asset amount in the following calculation (`_calculateAvailableCollateralToLiquidate()`), not as shares.

### Root Cause

https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L136

**Comment by charlesjhongc** [comment]
Escalate

I didn't know the impact field is a REQUIRED field to be considered as a valid issue since it's not specified in the doc nor is checked by the github bot. Also, it's marked as dup of a valid rewarded issue so I think it should not be considered as invalid.

The incorrect calculation is obvious and will cause unexpected behavior so I didn't explain the impact. Apologize for the inconvenience and will fix this for future audit.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I didn't know the impact field is a REQUIRED field to be considered as a valid issue since it's not specified in the doc nor is checked by the github bot. Also, it's marked as dup of a valid rewarded issue so I think it should not be considered as invalid.
> 
> The incorrect calculation is obvious and will cause unexpected behavior so I didn't explain the impact. Apologize for the inconvenience and will fix this for future audit.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
The Lead Judge is absolutely right here. 

A wrong variable is mentioned without having any impact or attack vector. 

According to the duplication rules, we cannot duplicate them. 
https://docs.sherlock.xyz/audits/real-time-judging/judging#ix.-duplication-rules

This issue does not have any impact. To duplicate the issue, it must have at least a Medium impact.

> Identify at least a Medium impact

Planning to reject the escalation and leave the issue as is.

**Comment by charlesjhongc** [comment]
My bad, didn't realize it's about duplication rules. Thanks for the explanation.

**Comment by cvetanovv** [comment]
No problem. Just try to have a better description, attack vector, and impact next time.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [charlesjhongc](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/370/#issuecomment-2393002160): rejected
