### ISSUE TITLE
trachev - Liquidations can leave positions at an unhealthier state, allowing to liquidate 100% of a position when only 50% should be allowed

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-new-scope-judging#394]
trachev

High

# Liquidations can leave positions at an unhealthier state, allowing to liquidate 100% of a position when only 50% should be allowed

### Summary

Liquidations are limited to either 100% (`MAX_LIQUIDATION_CLOSE_FACTOR = 1e4`) or 50% (`DEFAULT_LIQUIDATION_CLOSE_FACTOR = 0.5e4`) of a liquidated borrower's collateral. The limit is determined by the liquidated user's health factor: if it is less than 95% then full liquidation is possible and if it is more than 95% only 50% of their collateral should be at risk of being liquidated. The issue is that as the assets that comprise a reserve's collateral have different LTVs and liquidation thresholds it is possible that a position lowers its health factor after it has been liquidated. For example, if a position had a health factor of 97%, 50% of its collateral can be liquidated. However, if collateral assets with the highest liquidation thresholds are targeted, the health factor can drop below 95%, allowing to liquidate the entire collateral.

To put it simply, as this is the formula for calculating health factor:
`(totalCollateral * avgLiquidationThreshold%) / totalDebt`
the higher the average liquidation threshold, the higher the health factor, so liquidating assets with the highest liquidation threshold, and leaving those with a lower liquidation threshold will lower a position's health factor.

### Root Cause

- In [`executeLiquidationCall`](https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L94) there is no validation whether a liquidation leaves a position at a worse state than before it was liquidated.

### Attack Path

1. A position has borrowed 1000 USDC
2. Its collateral assets are comprised of: 
  - 600 DAI (600$), with a 100% liquidation threshold
  - 1 ETH, equal to 400$, with a 90% liquidation threshold
  - Average liquidation threshold = (600 * 100 + 400 * 90) / 1000 = 96%
3. The health factor is: 1000$ * 96% / 1000$ = 0.96
4. 0.96 < 1 so the position is liquidatable but only 50% of collateral can be liquidated, for simplicity we will ignore fees and liquidation bonuses
5. A liquidator liquidates the maximum 500 DAI of collateral, paying 500 USDC in debt
6. Average liquidation threshold = (100 * 100 + 400 * 90) / 500 = 92%
7. The health factor is: 500$ * 92$ / 500 = 0.92
8. The health factor has lowered and is now less than 0.95, thus the position can be fully liquidated

### Impact

Liquidators can liquidate 100% of positions which should only be liquidatable by 50%. Also as the health factor of positions can be lowered by liquidations, the chances of positions becoming insolvent and bad debt accruing increases.

### Mitigation

Consider validating that the health factor has not lowered after a partial liquidation occurs, thus encouraging liquidators to liquidate the collateral with lower liquidation thresholds first.

Duplicate of #335

**Comment by Joshuajee** [comment]
Escalate
This is not a duplicate of https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/338 but a duplicate of https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/335, as this involves health factor decreasing due to removing assets with the lowest LTV from the collateral baskets.

**Comment by sherlock-admin3** [comment]
> Escalate
> This is not a duplicate of https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/338 but a duplicate of https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/335, as this involves health factor decreasing due to removing assets with the lowest LTV from the collateral baskets.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by trachevgeorgi** [comment]
> Escalate This is not a duplicate of #338 but a duplicate of #335, as this involves health factor decreasing due to removing assets with the lowest LTV from the collateral baskets.

I believe it is a duplicate of both as both issues are stated in the report.

**Comment by Joshuajee** [comment]
The reason why this is not a duplicate of #338, is because the issues grouped under it deal with single collateral and the attack path is real. On the other hand, this issue talks about positions with multiple collaterals, such as #335. 
To be sincere this attack path is not realistic, there is no pool that will configure assets to have a 100% liquidation threshold any pool with such a threshold is designed to go insolvent.

**Comment by trachevgeorgi** [comment]
> The reason why this is not a duplicate of #338, is because the issues grouped under it deal with single collateral and the attack path is real. On the other hand, this issue talks about positions with multiple collaterals, such as #335. To be sincere this attack path is not realistic, there is no pool that will configure assets to have a 100% liquidation threshold any pool with such a threshold is designed to go insolvent.

Ok, I agree, this issue should be a duplicate of #335.

**Comment by cvetanovv** [comment]
I agree with the comments and the escalation. This issue is a duplicate of #335. Whether it remains valid will be decided by the escalation there.

Planning to accept the escalation and duplicate this issue with #335.

**Comment by WangSecurity** [comment]
Result:
High
Duplicate of #335

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [joshuajee](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/394/#issuecomment-2391517725): accepted
