### ISSUE TITLE
iamnmt - Missing update for the collateral reserve will allow liquidator to liquidate a healthy position

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-new-scope-judging#458]
iamnmt

Medium

# Missing update for the collateral reserve will allow liquidator to liquidate a healthy position

### Summary

The missing update for collateral reserve will cause the `healthFactor` to be calculated basing on a stale `liquidityIndex` of the collateral reserve, which will allow liquidator to liquidate a healthy position.

### Root Cause

The `liquidityIndex` of a reserve is only updated when `updateState` is called. The `liquidityIndex` will increase over time. At the beginning of the liquidation process, `updateState` is not called for `collateralReserve`, which will cause the `liquidityIndex` of `collateralReserve` will be less than the actual value

https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L94

The stale `liquidityIndex` is later used for calculating the `healthFactor` of the position

https://github.com/sherlock-audit/2024-06-new-scope/blob/c8300e73f4d751796daad3dadbae4d11072b3d79/zerolend-one/contracts/core/pool/logic/LiquidationLogic.sol#L110

Since the `liquidityIndex` is less than the actual value, the `totalCollateralInBaseCurrency` is less than the actual value, which could cause a healthy position to be liquidatable.

### Attack Path

Liquidate a position.

### Impact

A healthy position will be liquidatable, which will benefit the liquidator, and unfair for the borrower.

### Mitigation

Update the collateral reserve at the beginning of the liquidation process

`Pool.sol`

```diff
  function liquidate(address collat, address debt, bytes32 pos, uint256 debtAmt, DataTypes.ExtraData memory data) public {
+   forceUpdateReserve(collat);
    _liquidate(collat, debt, pos, debtAmt, data);
  }
```

**Comment by iamnmt** [comment]
Escalate

I believe this issue (#458) is not a duplicate of #199.

#199
- Root cause: CuratedVault#totalAssets does not update pool's liquidityIndex at the beginning
- Impact: An attacker can hijack yield from the vault

#458
- Root cause: The `liquidityIndex` of the collateral is not updated at the beginning of the liquidation.
- Impact: A liquidator can liquidate a healthy position.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> I believe this issue (#458) is not a duplicate of #199.
> 
> #199
> - Root cause: CuratedVault#totalAssets does not update pool's liquidityIndex at the beginning
> - Impact: An attacker can hijack yield from the vault
> 
> #458
> - Root cause: The `liquidityIndex` of the collateral is not updated at the beginning of the liquidation.
> - Impact: A liquidator can liquidate a healthy position.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by 0xjuaan** [comment]
Escalate

This is not a dupe of #199, and it's invalid. 

In LiquidationLogic, `liquidityIndex` does not need to be updated since `getNormalizedIncome()` is used to calculate the index, and this calculation is up to date by nature.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> This is not a dupe of #199, and it's invalid. 
> 
> In LiquidationLogic, `liquidityIndex` does not need to be updated since `getNormalizedIncome()` is used to calculate the index, and this calculation is up to date by nature.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
I agree with the escalation and @0xjuaan comment.

The root cause and the impact are different. Also, it is invalid because `liquidityIndex` is calculated by `getNormalizedIncome()`:

```solidity
uint256 liquidityIndex = collateralReserve.getNormalizedIncome();
```

Planning to accept the escalation and invalidate the issue.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin3** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xjuaan](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/458/#issuecomment-2393077838): accepted
- [iamnmt](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/458/#issuecomment-2391315105): rejected
