### ISSUE TITLE
KupiaSec - `getNormalizedDebt` returns inflated debt liquidity even if there's no debt

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-new-scope-judging#475]
KupiaSec

Medium

# `getNormalizedDebt` returns inflated debt liquidity even if there's no debt

## Summary
The `getNormalizedDebt` function miscalculates debt liquidity, inflating values even without `debtShares`, leading to an inaccurate portrayal of debt status and potential operational discrepancies.

## Vulnerability Detail
`ReserveLogic` has `getNormalizedDebt` function that calculates expected debt liquidity of a reserve at current timepoint.

```solidity
  function getNormalizedDebt(DataTypes.ReserveData storage reserve) internal view returns (uint256) {
    uint40 timestamp = reserve.lastUpdateTimestamp;

    //solium-disable-next-line
    if (timestamp == block.timestamp) {
      //if the index was updated in the same block, no need to perform any calculation
      return reserve.borrowIndex;
    } else {
>     return MathUtils.calculateCompoundedInterest(reserve.borrowRate, timestamp).rayMul(reserve.borrowIndex);
    }
  }
```
The function erroneously inflates the liquidity of debt, including interest, regardless of the actual debt status. In contrast, the `_updateIndexes` function correctly increases liquidity only when there is a non-zero debt for the reserve, highlighting a discrepancy in how debt liquidity is calculated and updated across these functions.

```solidity
  function _updateIndexes(DataTypes.ReserveData storage _reserve, DataTypes.ReserveCache memory _cache) internal {
    ...
    // Variable borrow index only gets updated if there is any variable debt.
    // cache.currBorrowRate != 0 is not a correct validation,
    // because a positive base variable rate can be stored on
    // cache.currBorrowRate, but the index should not increase
>   if (_cache.currDebtShares != 0) {
      uint256 cumulatedBorrowInterest = MathUtils.calculateCompoundedInterest(_cache.currBorrowRate, _cache.reserveLastUpdateTimestamp);
      _cache.nextBorrowIndex = cumulatedBorrowInterest.rayMul(_cache.currBorrowIndex).toUint128();
      _reserve.borrowIndex = _cache.nextBorrowIndex;
    }
  }
```

## Impact
It misleads users about debt accumulation, potentially discouraging their lending activities due to an inaccurate perception of financial obligations.

## Code Snippet
https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/ReserveLogic.sol#L69-L79

## Tool used
Manual Review

## Recommendation
`getNormalizedDebt` function should return `reserve.borrowIndex` when there's no debtShare.

**Comment by KupiaSecAdmin** [comment]
Escalate

Hope HoJ would consider the above comments. Thank you.

**Comment by sherlock-admin3** [comment]
> Escalate
> 
> Hope HoJ would consider the above comments. Thank you.

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
As far as I understand, `getNormalizedDebt()` is only used in `_getUserDebtInBaseCurrency()` and will not be called at all when there is no debt. There we have the following check:

https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/GenericLogic.sol#L192

```solidity
if (userTotalDebt != 0) userTotalDebt = userTotalDebt.rayMul(reserve.getNormalizedDebt());
```
Also, the issue does not have a valid attack path. The function itself is an `internal view`, and without showing which function calls it, there will be no impact.

Planning to reject the escalation and leave the issue as is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [KupiaSecAdmin](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/475/#issuecomment-2390863407): rejected
