### ISSUE TITLE
jah - wrong calculation in function  executeWithdraw

### ISSUE THREAD

**Issue by sherlock-admin4** [sherlock-audit/2024-06-new-scope-judging#498]
jah

High

# wrong calculation in function  executeWithdraw

### Summary

in **SupplyLogic** function **executeWithdraw**  if a user make params.amount  =   type(uint256).max line 121 will make the full amount balance  it will call getSupplyBalance  which will calculate the  the share with the lastSupplyLiquidtyIndexand with  the new one  and update params.amoun with  the collected amount  but when doing that  it is not update  **self.supplyShares** with the new one so in line 145  it will try to convert params.amount into share which will  might lead  for the function to revert because   **withdrawCollateral** will be called  and the calculated amount might be bigger than the   **self.supplyShares** which will revert  

### Root Cause

in SupplyLogic: 121 we need to udatete self.supplyShares with the new liquidity'
https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/SupplyLogic.sol#L145 

### Impact

unable to withdraw there own fund

**Comment by Demelew** [comment]
Escalate  
hey this is a valid bug let me try to explain it in SupplyLogic function executeWithdraw line 118   calculates the balance with cache.nextLiquidityIndex  and it uses  the function getSupplyBalance to calculate  and it returns the  self.supplyShares with the increase amount 
```solidity 
 function getSupplyBalance(DataTypes.PositionBalance storage self, uint256 index) public view returns (uint256 supply) {
    uint256 increase = self.supplyShares.rayMul(index) - self.supplyShares.rayMul(self.lastSupplyLiquidtyIndex);
    return self.supplyShares + increase;
  }
```
 and it update the variable with the returned amount  and in line 121  if the  params.amount == type(uint256).max) it update  params.amount with balance  and in line 145  when calculating **burnt.shares** it uses PositionBalanceConfiguration.withdrawCollateral to calculate  it subtracts     `self.supplyShares -= sharesBurnt;` and sharesBurnt is calulated  `    sharesBurnt = amount.rayDiv(index);`  amount is  params.amount so if we first  pass it as **type(uint256).max** on the first place  it will be  self.supplyShares + increase;  so when converting it will be greater than    self.supplyShares  because    self.supplyShares is not update it will revert  when subtracting **sharesBurnt** from **self.supplyShares**

**Comment by sherlock-admin3** [comment]
> Escalate  
> hey this is a valid bug let me try to explain it in SupplyLogic function executeWithdraw line 118   calculates the balance with cache.nextLiquidityIndex  and it uses  the function getSupplyBalance to calculate  and it returns the  self.supplyShares with the increase amount 
> ```solidity 
>  function getSupplyBalance(DataTypes.PositionBalance storage self, uint256 index) public view returns (uint256 supply) {
>     uint256 increase = self.supplyShares.rayMul(index) - self.supplyShares.rayMul(self.lastSupplyLiquidtyIndex);
>     return self.supplyShares + increase;
>   }
> ```
>  and it update the variable with the returned amount  and in line 121  if the  params.amount == type(uint256).max) it update  params.amount with balance  and in line 145  when calculating **burnt.shares** it uses PositionBalanceConfiguration.withdrawCollateral to calculate  it subtracts     `self.supplyShares -= sharesBurnt;` and sharesBurnt is calulated  `    sharesBurnt = amount.rayDiv(index);`  amount is  params.amount so if we first  pass it as **type(uint256).max** on the first place  it will be  self.supplyShares + increase;  so when converting it will be greater than    self.supplyShares  because    self.supplyShares is not update it will revert  when subtracting **sharesBurnt** from **self.supplyShares**
> 
> 
> 
> 

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by cvetanovv** [comment]
We have no issue here. 

Before the function continues to execute after updating `params.amount = balance;`, we have a function that validates the withdrawal:

https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/SupplyLogic.sol#L123

```solidity
ValidationLogic.validateWithdraw(params.amount, balance);
```

```solidity
  function validateWithdraw(uint256 amount, uint256 userBalance) internal pure {
    require(amount != 0, PoolErrorsLib.INVALID_AMOUNT);
    require(amount <= userBalance, PoolErrorsLib.NOT_ENOUGH_AVAILABLE_USER_BALANCE);
 }
```
If the amount is more than the user's balance, the function will revert.

Planning to reject the escalation and leave the issue as is.

**Comment by WangSecurity** [comment]
Result:
Invalid
Unique

**Comment by sherlock-admin4** [comment]
Escalations have been resolved successfully!

Escalation status:
- [demelew](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/498/#issuecomment-2393586481): rejected
