### ISSUE TITLE
0xc0ffEE - Borrower can not repay all position debt

### ISSUE THREAD

**Issue by sherlock-admin3** [sherlock-audit/2024-06-new-scope-judging#97]
0xc0ffEE

Medium

# Borrower can not repay all position debt

## Summary
Incorrect integration with `Pool` contract causes `NFTPositionManager` can not support borrowers to repay all position debt

## Vulnerability Detail
The `Pool` contract allows borrowers to repay [all position debt by setting `params.amount = type(uint256).max`](https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/BorrowLogic.sol#L128-L131).
However, [it always fails if `type(uint256).max` is used as amount to repay in `NFTPositionManager.repay()`](https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/positions/NFTPositionManager.sol#L69) function due to lack of balance because there will be almost impossible to have max uint256 balance amount

## Code Snippet
https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/pool/logic/BorrowLogic.sol#L128-L131

https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/positions/NFTPositionManager.sol#L69

https://github.com/sherlock-audit/2024-06-new-scope/blob/main/zerolend-one/contracts/core/positions/NFTPositionManagerSetters.sol#L105-L140

## Tool used

Manual Review

## Recommendation
Adding to logic to update `params.amount` in function `NFTPositionManager.repay` when user opts to repay all debt, by:
1. Update pool reserve to accrue interest
2. Query position debt balance
3. Set `params.amount` equals to debt balance above

Duplicate of #264

**Comment by thongtrungtran** [comment]
Escalate

I think this issue is not duplicate of #119. It should be a duplicate of #93. At the first glance, the issue shares the same root cause with #119 that the NFTPositionManager does not handle the case when `params.amount` is set to max uint256. However, the impact of this issue (same as #93) is different from #119 such that this issue blocks borrowers from paying all position debt at once. This dust debt leftover could accrues time by time, effectively grows position debt.
In the mean time, #119 only blocks the supplier from withdraw all funds at once, leaving dust supplied token which has no protocol economic risk

**Comment by coffiasd** [comment]
@thongtrungtran totally agree with you

**Comment by thongtrungtran** [comment]
also dup of #264

**Comment by cvetanovv** [comment]
I agree with the escalation that this issue(#97) and #93 are duplicates of #264. Whether they will be valid will be decided by the escalation there.

I am planning to accept the escalation and duplicate this issue(#97) and #93 with #264.

**Comment by WangSecurity** [comment]
Result:
Invalid
Duplicate of #264

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [thongtrungtran](https://github.com/sherlock-audit/2024-06-new-scope-judging/issues/97/#issuecomment-2390703313): accepted

**Comment by thongtrungtran** [comment]
@WangSecurity I think this issue should not be resolved as #264 is still not finalized yet.

**Comment by cvetanovv** [comment]
> I think this issue should not be resolved as #264 is still not finalized yet.

@thongtrungtran It doesn't matter. If #264 is valid, this issue will be valid too.
